{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test-autoconfigure",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.0.jar",
          "url": "spring-boot-test-autoconfigure-3.2.0.jar",
          "size": 218543,
          "sha512": "1e64d030fe8d37d96aa3d866e3f52c6e5caa404e5163dccddac0a3e60c6f5875304e753c0205be0ffe5aeec54df7465b3d34bf0f802514363b14e9b10548a8ee",
          "sha256": "91dbcbc47ae788c7662a32b4b0b435684bd5f0549fc24b1a1d08b1e5369606da",
          "sha1": "4d096363d61b38f3a4151c3a4460e7cd92c52ca8",
          "md5": "8d7c8ba286de606f24121fbd1afc77b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.0.jar",
          "url": "spring-boot-test-autoconfigure-3.2.0.jar",
          "size": 218543,
          "sha512": "1e64d030fe8d37d96aa3d866e3f52c6e5caa404e5163dccddac0a3e60c6f5875304e753c0205be0ffe5aeec54df7465b3d34bf0f802514363b14e9b10548a8ee",
          "sha256": "91dbcbc47ae788c7662a32b4b0b435684bd5f0549fc24b1a1d08b1e5369606da",
          "sha1": "4d096363d61b38f3a4151c3a4460e7cd92c52ca8",
          "md5": "8d7c8ba286de606f24121fbd1afc77b0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.0-javadoc.jar",
          "url": "spring-boot-test-autoconfigure-3.2.0-javadoc.jar",
          "size": 488232,
          "sha512": "f0a5c7180e9c935d3a718d994bd9af56e46d164ce9581580c5406de02217385bea08773684f85114d6f3be978104a85d65882da000d47a79814de30eb56cbe6d",
          "sha256": "a25e0d6526a983b0a9ee9cf53f7051c7e12c3f2305e6f3c66229c55381d15833",
          "sha1": "23c7b2fd5c91f5c4961142dfd9ce897290484957",
          "md5": "92ae124b1da063305e7bd4d095657a0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.0-sources.jar",
          "url": "spring-boot-test-autoconfigure-3.2.0-sources.jar",
          "size": 220725,
          "sha512": "a53c8229086e58e23b6916557c3054a7b7b608f01ef19633734c97d9af73bc2a36a4f7bfab043159321fac3a4df6777dad734b24f4d0234c1f5b28083363180f",
          "sha256": "264e6b906ce25f318f1ad000a10ca4c1f28cbbbdeceaeaf49062be854bb3d27c",
          "sha1": "f0fcbf4d3385b9a2cff4aef7cde11fdf2be0e6b6",
          "md5": "7c820260913ca4cf3289eec49bd2e638"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.0.jar",
          "url": "spring-boot-test-autoconfigure-3.2.0.jar",
          "size": 218543,
          "sha512": "1e64d030fe8d37d96aa3d866e3f52c6e5caa404e5163dccddac0a3e60c6f5875304e753c0205be0ffe5aeec54df7465b3d34bf0f802514363b14e9b10548a8ee",
          "sha256": "91dbcbc47ae788c7662a32b4b0b435684bd5f0549fc24b1a1d08b1e5369606da",
          "sha1": "4d096363d61b38f3a4151c3a4460e7cd92c52ca8",
          "md5": "8d7c8ba286de606f24121fbd1afc77b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-autoconfigure-maven-optional",
          "version": "3.2.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.0.jar",
          "url": "spring-boot-test-autoconfigure-3.2.0.jar",
          "size": 218543,
          "sha512": "1e64d030fe8d37d96aa3d866e3f52c6e5caa404e5163dccddac0a3e60c6f5875304e753c0205be0ffe5aeec54df7465b3d34bf0f802514363b14e9b10548a8ee",
          "sha256": "91dbcbc47ae788c7662a32b4b0b435684bd5f0549fc24b1a1d08b1e5369606da",
          "sha1": "4d096363d61b38f3a4151c3a4460e7cd92c52ca8",
          "md5": "8d7c8ba286de606f24121fbd1afc77b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-autoconfigure-maven-optional",
          "version": "3.2.0"
        }
      ]
    }
  ]
}
